name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1.3.3
      with:
        jvm: 8
    - name: Compile
      run: sbtn test:compile

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1.3.3
      with:
        jvm: 8
    - uses: olafurpg/setup-gpg@v3
    - run: .github/scripts/gpg-setup.sh
      env:
        PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
    - name: Release
      run: sbtn ci-release
      env:
        PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
        PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
        SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
